name = "TreeViews"
uuid = "0cdf7f9c-6f0a-11e8-33c6-7b5c10fffe5f"
authors = ["Sebastian Pfitzner <pfitzseb@physik.hu-berlin.de>"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
